### ISSUE TITLE
Disclosure control function

### ISSUE THREAD

**Issue by psychty** [psychty/secondary_care#1]
I have written a simple disclosure control function for field values to supress counts of 1-7, or round to nearest five.

The function currently only accepts a single argument and I need it to run on a column or series of values.

This is likely a PEBCAK issue.

**Comment by mattischrome** [comment]
I think you're right. I wrote a version using dplyr::case_when, which might be a case(_when) of using a sledgehammer to crack a nut, but it is vectorised by default, and should work on data frame columns nicely.

**Comment by psychty** [comment]
This works great, thanks.
